// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpqs_l7nkvH9TPeUoJnioo-07fElyX9tY',
    appId: '1:392192827788:web:5120133446e5e134b7b6a9',
    messagingSenderId: '392192827788',
    projectId: 'insta-stonks',
    authDomain: 'insta-stonks.firebaseapp.com',
    storageBucket: 'insta-stonks.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAigbb0B96Ryj92fe41ME17zoGYcAtOTao',
    appId: '1:392192827788:android:4d494c44770e5d5ab7b6a9',
    messagingSenderId: '392192827788',
    projectId: 'insta-stonks',
    storageBucket: 'insta-stonks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGwVh1Mp0zkKqI4eoPDvpQjc8VnZ337gs',
    appId: '1:392192827788:ios:ab117006aeb263d1b7b6a9',
    messagingSenderId: '392192827788',
    projectId: 'insta-stonks',
    storageBucket: 'insta-stonks.firebasestorage.app',
    iosBundleId: 'com.example.instaStonks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGwVh1Mp0zkKqI4eoPDvpQjc8VnZ337gs',
    appId: '1:392192827788:ios:ab117006aeb263d1b7b6a9',
    messagingSenderId: '392192827788',
    projectId: 'insta-stonks',
    storageBucket: 'insta-stonks.firebasestorage.app',
    iosBundleId: 'com.example.instaStonks',
  );
}
